version: '3'

services:
  app:
    build: .
    container_name: app_navar
    ports: 
      - 1313:1313

  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    network_mode: host
    volumes:
      - ./notebooks:/solution/notebooks
      - ./data:/solution/data
      - ./src:/solution/src
      - ./models:/solution/models
    ports:
      - 8888:8888
    

      

