# Use an official Python runtime as a parent image
FROM jupyter/base-notebook

# Set the working directory to /app
make WORKDIR /solution
COPY requirements.txt /solution
RUN pip install --trusted-host pypi.python.org -r requirements.txt

COPY . /solution

ENV JUPYTER_ENABLE_LAB=yes

# The entrypoint is not enterilly necessary when you set the env variable above
# ENTRYPOINT ["start.sh", "jupyter lab"]

